### ISSUE TITLE
database name in utf-8 cannot be accepted.

### ISSUE THREAD

**Issue by uirousan** [mfenniak/pg8000#69]
Hi!

I am using pg8000 1.10.1.  
When the name of the queried database includes utf-8 string, `UnicodeEncodeError` is emitted.  

For example:

    import pg8000
    conn = pg8000.connect(user="tester", database="テストDB", password="xxxxx")

receives following error, 

    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

I found *core.py* includes `database.encode("ascii")`.  
Shouldn't it be `database.encode(self._cilent_encoding)`?
I found several `.encode("ascii")` in *core.py*.

**Comment by tlocke** [comment]
Hi, I've fixed this at https://github.com/mfenniak/pg8000/commit/346e309c2b8cda3a776f24403ae51eb35f8d1881. I haven't included test for it as I couldn't work out a good way of testing it. Let me know if you can think of a good way of testing.

**Comment by mfenniak** [comment]
@tlocke -- the database name is sent as part of the StartupMessage packet, and that would be sent before we receive the client encoding   Reading through the __init__ method, it appears that _client_encoding will still have the "ascii" value that it defaults to where this commit modifies the code since we couldn't have received and handled a PARAMETER_STATUS message at this point yet.  Am I mistaken?

**Comment by tlocke** [comment]
Yes you're right @mfenniak! Arghhh!! The only things I can think of are:

1. Set the default to utf8 rather than ascii. That way it won't break for any existing users, and it'll work for most cases.

2. Going further we could have an optional 'bootstrap_encoding' parameter for the connect() method that's used until we get the client_encoding back from the server.

Or something else...any ideas?

**Comment by mfenniak** [comment]
It'd probably make sense to look at how psql / libpq behave, possibly by inspecting the data on the wire.  I didn't even know that non-ascii database names were possible because they're sent so early in the protocol.

My guess is that there's a default encoding that's used before the client_encoding is negotiated, or that the client_encoding can be specified by the client as part of the startup message or something else pre-authentication which would influence the server's interpretation of the strings in the startup message.

**Comment by tlocke** [comment]
I've done some experiments and setting the client encoding in the StartupMessage doesn't affect how the database name is interpreted. I've come across this email which explains what's going on:

http://www.postgresql.org/message-id/1330344173.7111.23.camel@vanquo.pezone.net

> In the connection request, you effectively need to specify the user name
> (and database name) as bytes in the encoding that you created them in.
> I don't think this is documented in an obvious way.

So I now think we should say that the `connect()` parameters `user` and `database` are byte strings, and pass them unmodified in StartupMessage. To make it backwardly compatible for Python 3 users we can detect if the parameters are `str` or `bytes` and if they are `str` we can encode them with utf8. For Python 2 users there are no backward compatibility problems. I'll put the code up on my repo in a minute to show you what I mean.

**Comment by tlocke** [comment]
I've put a commit that does this on my repo at https://github.com/tlocke/pg8000/commit/04a9d3bd93f7b589bdd89ee2912bea596c0a0dfa.

**Comment by mfenniak** [comment]
Looks good to me. :-)

**Comment by tlocke** [comment]
Cool, I've pushed that to the main repo https://github.com/mfenniak/pg8000/commit/04a9d3bd93f7b589bdd89ee2912bea596c0a0dfa.

**Comment by uirousan** [comment]
Thank you for implementing the utf-8 database name functionality! 
Sorry for my delay due to my travel.

**Comment by tlocke** [comment]
This seems like it's fixed, so I'll mark it closed.
